# Generated by Django 4.0.3 on 2023-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_fooditem_note_alter_fooditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
