# Generated by Django 4.0.3 on 2023-04-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_measure_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
