# Generated by Django 4.0.3 on 2023-04-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_step_food_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
