# Generated by Django 4.0.3 on 2023-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_created_alter_recipe_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
