# Generated by Django 4.0.3 on 2023-04-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
