# Generated by Django 4.0.3 on 2023-04-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_rating_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='updated',
        ),
    ]
